@username = alexcarrega
@password = test-me
@url = http://0.0.0.0:9998


### Login
# @name login

POST {{url}}/auth/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### Get tokens

@access_token = {{login.response.body.access_token}}
@refresh_token = {{login.response.body.refresh_token}}

## Category

### Category POST

# @name category_post

POST {{url}}/me/category
Authorization: Bearer {{access_token}}

{
    "name": "test"
}

### Get Category ID

@category_id = {{category_post.response.body.id}}

### Category Created GET

GET {{url}}/me/category/created
Authorization: Bearer {{access_token}}

### Category Updated GET

GET {{url}}/me/category/updated
Authorization: Bearer {{access_token}}

### Category GET

GET {{url}}/me/category/{{category_id}}
Authorization: Bearer {{access_token}}

### Category PUT

PUT {{url}}/me/category/{{category_id}}
Authorization: Bearer {{access_token}}

{
    "name": "updated-test2"
}

###
