@username = alexcarrega
@password = test-me
@url = http://0.0.0.0:9998


### Login
# @name login

POST {{url}}/auth/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### Get tokens

@access_token = {{login.response.body.access_token}}
@refresh_token = {{login.response.body.refresh_token}}

## Task

### Task POST

# @name task_post

POST {{url}}/me/task
Authorization: Bearer {{access_token}}

{
    "name": "test",
    "category_id": 3,
    "status": "todo"
}

### Get Task ID

@task_id = {{task_post.response.body.id}}

### Task Created GET

GET {{url}}/me/task/created
Authorization: Bearer {{access_token}}

### Task Updated GET

GET {{url}}/me/task/updated
Authorization: Bearer {{access_token}}

### Task GET

GET {{url}}/me/task/{{task_id}}
Authorization: Bearer {{access_token}}

### Task PUT

PUT {{url}}/me/task/{{task_id}}
Authorization: Bearer {{access_token}}

{
    "status": "started"
}

### Task PUT

PUT {{url}}/me/task/{{task_id}}
Authorization: Bearer {{access_token}}

{
    "status": "completed"
}
