@username = alexcarrega
@password = test-me
@url = http://0.0.0.0:9998


### Login
# @name login

POST {{url}}/auth/token
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### Get tokens

@access_token = {{login.response.body.access_token}}
@refresh_token = {{login.response.body.refresh_token}}

## Tag

### Tag POST

# @name tag_post

POST {{url}}/me/tag
Authorization: Bearer {{access_token}}

{
    "name": "test"
}

### Get Tag ID

@tag_id = {{tag_post.response.body.id}}

### Tag Created GET

GET {{url}}/me/tag/created
Authorization: Bearer {{access_token}}

### Tag Updated GET

GET {{url}}/me/tag/updated
Authorization: Bearer {{access_token}}

### Tag GET

GET {{url}}/me/tag/{{tag_id}}
Authorization: Bearer {{access_token}}

### Tag PUT

PUT {{url}}/me/tag/{{tag_id}}
Authorization: Bearer {{access_token}}

{
    "name": "updated-test2"
}

###
